local_repository(
    name = "obazl_rules_ocaml",
    path = ".."
)

load("@obazl_rules_ocaml//ocaml:deps.bzl",
     "ocaml_configure_tooling",
     # "ocaml_repositories",
     # "ocaml_home_sdk",
     "ocaml_register_toolchains")

ocaml_configure_tooling()

ocaml_register_toolchains(installation="host")

